// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function StartBuild():Promise<void>;

export function StartGitHubLogin():Promise<auth.UserCodeInfo>;
