// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['backend']['App']['SelectDirectory']();
}

export function StartBuild(arg1) {
  return window['go']['backend']['App']['StartBuild'](arg1);
}
