// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function SelectDirectory():Promise<string>;

export function StartBuild(arg1:Record<string, any>):Promise<void>;

export function StartGitHubLogin():Promise<auth.UserCodeInfo>;
