// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloneRepo(arg1) {
  return window['go']['backend']['App']['CloneRepo'](arg1);
}

export function DeleteRepo(arg1) {
  return window['go']['backend']['App']['DeleteRepo'](arg1);
}

export function GetRecentRepos() {
  return window['go']['backend']['App']['GetRecentRepos']();
}

export function GetRepoStatus(arg1) {
  return window['go']['backend']['App']['GetRepoStatus'](arg1);
}

export function ListClonedRepos() {
  return window['go']['backend']['App']['ListClonedRepos']();
}

export function Ping() {
  return window['go']['backend']['App']['Ping']();
}

export function SelectDirectory() {
  return window['go']['backend']['App']['SelectDirectory']();
}

export function StartBuild(arg1) {
  return window['go']['backend']['App']['StartBuild'](arg1);
}

export function StartGitHubLogin() {
  return window['go']['backend']['App']['StartGitHubLogin']();
}
