// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteGitHubLogin() {
  return window['go']['backend']['App']['CompleteGitHubLogin']();
}

export function StartBuild() {
  return window['go']['backend']['App']['StartBuild']();
}

export function StartGitHubLogin() {
  return window['go']['backend']['App']['StartGitHubLogin']();
}
