// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {repo} from '../models';

export function CloneRepo(arg1:string):Promise<string>;

export function DeleteRepo(arg1:string):Promise<void>;

export function GetRecentRepos():Promise<Array<auth.Repo>>;

export function GetRepoStatus(arg1:string):Promise<repo.RepoStatus>;

export function ListClonedRepos():Promise<Array<string>>;

export function SelectDirectory():Promise<string>;

export function StartBuild(arg1:Record<string, any>):Promise<void>;

export function StartGitHubLogin():Promise<auth.UserCodeInfo>;
